# Generated by Django 4.2.8 on 2024-02-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='other_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
