# Generated by Django 4.2.8 on 2024-01-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_productvariant_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='ProductVariation',
        ),
        migrations.RenameModel(
            old_name='ProductVariantAttribute',
            new_name='ProductVariationAttribute',
        ),
        migrations.RenameModel(
            old_name='ProductVariantImage',
            new_name='ProductVariationImage',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Thuộc tính', 'verbose_name_plural': 'Thuộc tính'},
        ),
        migrations.AlterModelOptions(
            name='attributeoption',
            options={'verbose_name': 'Giá trị thuộc tính', 'verbose_name_plural': 'Giá trị thuộc tính'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Nhãn hàng', 'verbose_name_plural': 'Nhãn hàng'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartdetails',
            options={'verbose_name': 'Chi tiết giỏ hàng', 'verbose_name_plural': 'Chi tiết giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='likeproduct',
            options={'verbose_name': 'Sản phẩm yêu thích', 'verbose_name_plural': 'Sản phẩm yêu thích'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Biến thể sản phẩm', 'verbose_name_plural': 'Biến thể sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productvariationattribute',
            options={'verbose_name': 'Thuộc tính sản phẩm', 'verbose_name_plural': 'Thuộc tính sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productvariationimage',
            options={'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.RenameField(
            model_name='productvariationimage',
            old_name='product_variant',
            new_name='product_variation',
        ),
    ]
