# Generated by Django 4.2.8 on 2024-01-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_productvariant_productvariation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='product_variant',
            new_name='product_variation',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_variant',
            new_name='product_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_variant',
        ),
        migrations.RemoveField(
            model_name='productvariationattribute',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='main_variation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_variation', to='api.productvariation'),
        ),
        migrations.AddField(
            model_name='productvariationattribute',
            name='product_variation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_attribute', to='api.productvariation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='api.product'),
        ),
    ]
