# Generated by Django 4.2.8 on 2024-01-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_product_variant_cartdetails_product_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariationattribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariationattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
        ),
        migrations.DeleteModel(
            name='AttributeOption',
        ),
    ]
