# Generated by Django 4.2.8 on 2024-01-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productvariationattribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='discount_percentage',
        ),
    ]
