# Generated by Django 4.2.8 on 2024-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_productvariation_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariationattribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
