# Generated by Django 4.2.8 on 2024-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_productvariationattribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variations',
            field=models.ManyToManyField(related_name='product_variations', to='api.productvariation'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='images',
            field=models.ManyToManyField(related_name='images', to='api.productvariationimage'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product_variation_attributes',
            field=models.ManyToManyField(through='api.ProductVariationAttribute', to='api.attribute'),
        ),
    ]
