# Generated by Django 4.2.8 on 2024-02-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_product_variations_productvariation_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_variations',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_variations', to='api.productvariation'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='api.productvariationimage'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_variation_attributes',
            field=models.ManyToManyField(blank=True, null=True, through='api.ProductVariationAttribute', to='api.attribute'),
        ),
    ]
