# Generated by Django 4.2.8 on 2024-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_product_variations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product_variation_attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_variation_attributes', through='api.ProductVariationAttribute', to='api.attribute'),
        ),
    ]
